### ISSUE TITLE
Add dependencies to README.md

### ISSUE THREAD

**Issue by f-skold** [Martin7mind/ghomeghub#1]
In my Ubuntu 20.04 focal, I had to issue this command to get things to build:

    sudo apt-get install libavahi-compat-libdnssd-dev

**Comment by f-skold** [comment]
Not so sure the packages I listed above was the right ones, I got this when I tried to run the program.

Not sure why I get this error message 

(Maybe this should have been a separate Issue.)

```
$ node .
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
/home/skold/src/ghomeghub/node_modules/mdns/lib/browser.js:86
  dns_sd.DNSServiceBrowse(self.serviceRef, flags, ifaceIdx, '' + requested_type,
         ^

Error: dns service error: unknown
    at new Browser (/home/skold/src/ghomeghub/node_modules/mdns/lib/browser.js:86:10)
    at Object.create [as createBrowser] (/home/skold/src/ghomeghub/node_modules/mdns/lib/browser.js:114:10)
    at Object.<anonymous> (/home/skold/src/ghomeghub/node_modules/google-home-push/index.js:6:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
```
